<?php
require_once 'init/initialize_general.php';
$thisPage = "Support";
?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <base target="_self">
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Instaforex Nigeria | Frequently Asked Questions</title>
        <meta name="title" content="Instaforex Nigeria | Frequently Asked Questions" />
        <meta name="keywords" content="">
        <meta name="description" content="">
        <?php require_once 'layouts/head_meta.php'; ?>
    </head>
    <body>
        <?php require_once 'layouts/header.php'; ?>
        <!-- Main Body: The is the main content area of the web site, contains a side bar  -->
        <div id="main-body" class="container-fluid">
            <div class="row no-gutter">
                <?php require_once 'layouts/topnav.php'; ?>
                <!-- Main Body - Content Area: This is the main content area, unique for each page  -->
                <div id="main-body-content-area" class="col-md-8 col-md-push-4 col-lg-9 col-lg-push-3">
                    
                    <!-- Unique Page Content Starts Here
                    ================================================== -->
                    
                    <div class="section-tint super-shadow">
                        <div class="row">
                            <div class="col-sm-12 text-danger">
                                <h4><strong>Frequently Asked Questions</strong></h4>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-sm-12">
                                <p>We have compiled answers to our frequently asked questions below, if your question is not answered, please <a href="contact_info.php">contact us</a> immediately.</p>
                                <div class="panel-group" id="accordion">
                                    <div class="panel panel-default">
                                        <div class="panel-heading"><h5 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse1">How Can I fund my Instaforex account?</a></h5></div>
                                        <div id="collapse1" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>You can fund your Instaforex Account through our Website here, click on <a href="deposit_funds.php" target="_blank">Fund Account</a> and follow the process through.</p>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="panel panel-default">
                                        <div class="panel-heading"><h5 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse2">Where can I get my pass code?</a></h5></div>
                                        <div id="collapse2" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>Your Pass Code is a security code generated by you before you make withdrawals for the first time on our website, subsequent withdrawals requires this pass code. Please keep it safe and do not share it with anyone.</p>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="panel panel-default">
                                        <div class="panel-heading"><h5 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse3">I have forgotten my Passcode, what do I do?</a></h5></div>
                                        <div id="collapse3" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>You can recover your passcode by clicking on the "Click Here to Recover Your Passcode", just below the column were you are to input your passcode.</p>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="panel panel-default">
                                        <div class="panel-heading"><h5 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse4">How Often can I fund my Instaforex Account?</a></h5></div>
                                        <div id="collapse4" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>Funds can be transferred 24 hours a day, seven days a week.</p>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="panel panel-default">
                                        <div class="panel-heading"><h5 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse5">How can I withdraw from my instaforex account?</a></h5></div>
                                        <div id="collapse5" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>Please visit instafxng.com, click on withdraw and follow the process through.</p>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="panel panel-default">
                                        <div class="panel-heading"><h5 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse6">After Inputting my passcode and I submit, but I don't get an SMS code. What do I do?</a></h5></div>
                                        <div id="collapse6" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>You not getting an SMS code might be due to bad network. Please wait for 2 minutes and try again. If you still do not get an SMS, please call any of our support lines.</p>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="panel panel-default">
                                        <div class="panel-heading"><h5 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse7">How long is the SMS code valid?</a></h5></div>
                                        <div id="collapse7" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>The SMS code expires after 5 minutes.</p>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="panel panel-default">
                                        <div class="panel-heading"><h5 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse8">How long does it take for my account to be funded?</a></h5></div>
                                        <div id="collapse8" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>Funding is Instant</p>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="panel panel-default">
                                        <div class="panel-heading"><h5 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse9">What Payment Method does InstafxNg use?</a></h5></div>
                                        <div id="collapse9" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>Funding your InstaForex account with us is fast and easy. You can credit your IFX account in Naira using any of the following methods:</p>
                                                <ul class="fa-ul">
                                                    <li><i class="fa-li fa fa-check-square-o icon-tune"></i>Paga account</li>
                                                    <li><i class="fa-li fa fa-check-square-o icon-tune"></i>Verve, MasterCard or Visa</li>
                                                    <li><i class="fa-li fa fa-check-square-o icon-tune"></i>Cash Payment to the bank</li>
                                                    <li><i class="fa-li fa fa-check-square-o icon-tune"></i>Internet bank transfer</li>
                                                    <li><i class="fa-li fa fa-check-square-o icon-tune"></i>Bank transfer at the bank</li>
                                                    <li><i class="fa-li fa fa-check-square-o icon-tune"></i>ATM Transfer / POS Transfer</li>
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="panel panel-default">
                                        <div class="panel-heading"><h5 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse10">What is the Minimum deposit Amount?</a></h5></div>
                                        <div id="collapse10" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>Minimum deposit is $5</p>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="panel panel-default">
                                        <div class="panel-heading"><h5 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse11">What is the Minimum withdrawal Amount?</a></h5></div>
                                        <div id="collapse11" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>Minimum withdrawal is $10</p>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="panel panel-default">
                                        <div class="panel-heading"><h5 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse12">I would like to learn how to trade Forex profitably, how do I start?</a></h5></div>
                                        <div id="collapse12" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>We currently have a free training you can take advantage of. Visit <a href="https://instafxng.com/fxacademy/">www.instafxng.com/fxacademy/</a> to start.</p>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="panel panel-default">
                                        <div class="panel-heading"><h5 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse13">What is a transaction ID?</a></h5></div>
                                        <div id="collapse13" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>It is an ID generated every time you want to fund your account. It looks like this "IFX1234567890".</p>
                                            </div>
                                        </div>
                                    </div>
                                    
                                    <div class="panel panel-default">
                                        <div class="panel-heading"><h5 class="panel-title"><a data-toggle="collapse" data-parent="#accordion" href="#collapse14">How do I notify for my payment</a></h5></div>
                                        <div id="collapse14" class="panel-collapse collapse">
                                            <div class="panel-body">
                                                <p>Visit our website after payment in the bank then click on ‘click here for payment notification', type in your transaction ID and fill the form.</p>
                                            </div>
                                        </div>
                                    </div>
                                    
                                </div>
                            </div>
                        </div>
                        

                    </div>

                    <!-- Unique Page Content Ends Here
                    ================================================== -->
                    
                </div>
                <!-- Main Body - Side Bar  -->
                <div id="main-body-side-bar" class="col-md-4 col-md-pull-8 col-lg-3 col-lg-pull-9 left-nav">
                <?php require_once 'layouts/sidebar.php'; ?>
                </div>
            </div>
        </div>
        <?php require_once 'layouts/footer.php'; ?>
    </body>
</html>