CREATE TABLE `sms_records` (
 `record_id` int(11) NOT NULL AUTO_INCREMENT,
 `phone_no` varchar(50) NOT NULL,
 `message` varchar(255) NOT NULL,
 `status` varchar(50) NOT NULL COMMENT '1701 = SUCCESS  1702 = INVALID URL/PARAMETERS  1703 = INVALID USERNAME/PASSWORD  1704 = INSUFFICIENT CREDIT  1705 = MOBILES TO LONG (MAX.500)  1706 = INTERNAL ERROR',
 `sender` varchar(50) NOT NULL,
 `created` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
 PRIMARY KEY (`record_id`),
 UNIQUE KEY `record_id` (`record_id`)
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8