CREATE TABLE IF NOT EXISTS `walk_in_client` (
 `id` INT(11) NOT NULL AUTO_INCREMENT,
 `admin_code` VARCHAR(5) NULL,
 `full_name` VARCHAR(100) NOT NULL,
 `phone` VARCHAR(11) NOT NULL,
 `email_address` VARCHAR(100) NOT NULL,
 `trans_type` TEXT NOT NULL,
 `client_feedback` TEXT NULL,
 `time_in` TIME NOT NULL,
 `time_out` TIME NOT NULL,
 `issues_record` TEXT NULL,
 `admin_comment` TEXT NULL,
 `office_location` INT(11) NOT NULL,
 `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `updated` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (`id`))
 ENGINE = InnoDB;

CREATE TABLE IF NOT EXISTS `office_location` (
 `id` INT(11) NOT NULL AUTO_INCREMENT,
 `location` VARCHAR(255) NOT NULL,
 `created` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
 `updated` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
 PRIMARY KEY (`id`))
 ENGINE = InnoDB